GET http://localhost:3001/todos HTTP/1.1

###

POST http://localhost:3001/todo/new 
Content-Type: application/json

{
    "text": "Pick up boat"
}

###

DELETE http://localhost:3001/todo/delete/61226f28ccd6614a54cfc695

###

PUT http://localhost:3001/todo/update/612270c6ccd6614a54cfc699
Content-Type: application/json
{
"text": "Go Shopping for Milk"
}
